name 'razorsedge-openlldp'
version '0.2.0'

author 'razorsedge'
license 'Apache License, Version 2.0'
project_page 'https://github.com/razorsedge/puppet-openlldp'
source 'https://github.com/razorsedge/puppet-openlldp.git'
summary 'Open-LLDP installation and management.'
description 'This module manages the installation Open-LLDP, a GPL licensed implementation of the Link Layer Discovery Protocol.'
dependency 'puppetlabs/stdlib', '>=2.3.0'
